<?php
include "../config/auth.php"; 
requireRole([1,2]);
include "../config/db.php";
include '../includes/header.php';
?>
<head>
    <link rel="stylesheet" href="../assets/css/payslip.css">
</head>
<main>
    <section>
        <div class="company-name">
            <div class="company-head">
                <h3>Mind2web</h3>
                <p>Mohali,India</p>
            </div>
            <div class="company-logo">
                <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4ufOjMD7ZU4Ww2oHuSAuX1nTeLe6hZu_gIA&s">
            </div>
        </div>
        <hr>
        <div class="month">
            <h3>Payslip for the month of March 2025</h3>
        </div>


<div class="employee"><h3>Employee Pay Summary</h3></div>
        <div class="employee-summary">
            <div class="employee-data">
                <div class="employee-head">
                <p>Employee Name</p>
                <p>Job Position</p>
                <p>Date of Joining</p>
                <p>Pay Month</p>
                <p>Pay Date</p>

                </div>
                <div class="employee-result">
                <p>: Mohit Kumar</p>
                <p>: Software trainee</p>
                <p>: 30/9/2025</p>
                <p>: Jan 2025</p>
                <p>: 6/11/2025</p>
                </div>

            </div>
            <div class="employeenet-pay">
                <h3>Employee Net Pay</h3>
                <p>₹87,500</p>
                <p class="paid">Paid Days : 31 | LOP Days : 0 </p>
            </div>
        </div>
        <hr>
        
        <div class="salary-details">
            <table>
                <thead>
                    <tr>
                        <th>Earnings</th>
                        <th>Amount</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Basic Salary</td>
                        <td>₹8988</td>
                    </tr>
                    <tr>
                        <td>House Rent Allowance</td>
                        <td>₹4000</td>
                    </tr>
                    <tr class="gross">
                        <td>Gross Earnings</td>
                        <td>₹14000</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <hr>

        <div class="attendance-details">
            <table>
                <thead>
                    <tr>
                        <th>Attendence</th>
                        <th>Total Days</th>
                    </tr>
                </thead>
                <tbody>
                     <tr>
                        <td>Working Days</td>
                        <td>30</td>
                    </tr>
                    <tr>
                        <td>Present Days</td>
                        <td>23</td>
                    </tr>
                    <tr>
                        <td>Absent Days</td>
                        <td>1</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <hr>

        <div class="deduction-details">
            <table>
                <thead>
                    <tr>
                        <th>Deductions</th>
                        <th>(-)Amounts</th>
                    </tr>
                </thead>
                <tbody>
                     <tr>
                        <td>Professional Tax</td>
                        <td>₹200</td>
                    </tr>
                    <tr>
                        <td>Absent Days</td>
                        <td>₹400</td>
                    </tr>
                     <tr class="deduction">
                        <td>Total Deductions</td>
                        <td>₹600</td>
                    </tr>
                    <tr class="netpay">
                        <td>Net Pay (Gross Earnings - Deductions)</td>
                        <td>₹50000</td>
                    </tr>
                   
                </tbody>
            </table>
        </div>
        <div class="totalnetpay">
            <h3>Total Net Payable <span>₹50000</span> (Indian Rupees Fifty Thousand)</h3>
        </div>
<hr>
        <div class="note">
            <p>--This Document is generated by Mind2Web Payroll, therefore ,a signature is not required--</p>
        </div>
    </section>
    <a class="download" href="download.php">Download Pay Slip</a>
</main>
